name: publish

on:
  push:
    branches: [ master ]
    tags: ['**']

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get git tag
        id: git_info
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - name: Resolve image tags
        id: resolve
        env:
          git_tag: ${{ steps.git_info.outputs.tag }}
        run: |
          dock_image="${GITHUB_REPOSITORY,,}"  # to lower case
          tag="${git_tag:-latest}"  # if build triggered by tag, use tag name
          echo "::set-output name=tag::$dock_image:$tag"
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,ppc64le
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.buildx.outputs.platforms }}
          push: true
          tags: ${{ steps.resolve.tag }}
